name: ${PROJECT_NAME}

networks:
  host-api-network:
    name: host-api-network
    external: true
services:
  api_1:
    build: ./api_1
    networks:
      - host-api-network
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - TZ=${TZ}
      - ENVIRONMENT=${ENVIRONMENT:-local}
      - LOGS_ROOT=${LOGS_ROOT:-xml/}
      - LOGS_MIRROR=${LOGS_MIRROR:-/srv/btl_mirror}
      - LOGS_STORE=${LOGS_STORE:-/srv/btl_store/gz}
      - API_FATHER_URL=http://api_father:9000
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8081/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  api_2:
    build: ./api_2
    networks:
      - host-api-network
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      - TZ=${TZ}
      - ENVIRONMENT=${ENVIRONMENT:-local}
      - LOGS_ROOT=${LOGS_ROOT:-xml/}
      - LOGS_MIRROR=${LOGS_MIRROR:-/srv/btl_mirror}
      - LOGS_STORE=${LOGS_STORE:-/srv/btl_store/gz}
      - API_FATHER_URL=http://api_father:9000
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8082/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  api_mother:
    build: ./api_mother
    container_name: host-api-service-api_mother-1
    networks:
      - host-api-network
    restart: unless-stopped
    ports:
      - "8083:8083"
    environment:
      - TZ=${TZ}
      - ENVIRONMENT=${ENVIRONMENT:-local}
      - LOGS_ROOT=${LOGS_ROOT:-xml/}
      - LOGS_RAW=/srv/btl/raw
      - LOGS_STORE=/srv/btl/gz
    volumes:
      - ./data/btl:/srv/btl:rw
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8083/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
